### PR TITLE
proposed french translation

### PR DESCRIPTION
**Pull request by patlachance**
Please find a contribution for french translation. Not tested.

### CODE REVIEW

**Comment by LazyT** [comment]
Hi patlachance,

thanks for your work!

I've extended the about dialog to show translation infos. Could you please update the new strings (your name and language)?

Are you interested in translating the help file (xml strings) too? Contact me via email and I'll send you the files and details (not yet in git)...

Thanks,
Thomas

**Comment by patlachance** [comment]
Hi Thomas

Thanks for adding translator info in the about dialog. I would be pleased
to help translating the documentation but I'm running out of time at the
moment. Maybe later!

But I don't know what to do. Do I have to change the following code or
duplicate it? If I duplicate it, will it change the line numbers? (btw I
had to manually change a bunch of line numbers manually in the translation
file: any trick to automate it?)

+ <message>
+ <location filename="../mainwindow.h" line="32"/>
+ <source>LazyT</source>
+ <translatorcomment>hint for translators: please enter YOUR NAME here
(will be shown in about dialog)</translatorcomment>
+ <translation>LazyT</translation>
+ </message>
+ <message>
+ <location filename="../mainwindow.h" line="33"/>
+ <source>English</source>
+ <translatorcomment>hint for translators: please enter YOUR LANGUAGE here
(will be shown in about dialog)</translatorcomment>
+ <translation>Deutsch</translation>
+ </message>

2016-05-04 13:25 GMT+02:00 Thomas Löwe <notifications@github.com>:

**Comment by LazyT** [comment]
Hi again,

> I would be pleased to help translating the documentation but I'm running out of time at the moment.

No problem, customers never read documentations. :smirk:

> But I don't know what to do.

Did you translate it "manually"? :flushed:

It's really simple:
- add french to "obpm.pro" ("TRANSLATIONS += lng/obpm_de.ts lng/obpm_fr.ts")
- update translations ("lupdate -no-obsolete obpm.pro") -> copy your already existing translated file to "lng/obpm_fr.ts" before or you get a new empty file!
- translate all new/updated strings ("linguist lng/obpm_fr.ts")
- click on "File -> Release" to create the tranlation file "obpm_fr.qm" and run obpm to see if all is fine

The "lupdate" (command line tool) and "linguist" (gui) are components of [Qt](https://www.qt.io/download-open-source/).

Your current file is broken ("+" signs at line 1280/1281) and the strings "LazyT" should be replaced by "patlachance" (or whatever should be shown in about dialog) and "English" should be "Français".

I can fix this for you, checkin to github and close this request or would you like to try the above yourself?

Greetings,
Thomas

**Comment by patlachance** [comment]
Ah ok, thanks! When I help translating project, I usually just provide
translation in text files I find related to languages using simple text
editor  and don't usually rebuild the project. But I'll try one day to
recompile OBPM by myself! I made the changes, so you can merge if
everything seems good to you.

2016-05-05 9:46 GMT+02:00 Thomas Löwe <notifications@github.com>:

> Hi again,
>
> I would be pleased to help translating the documentation but I'm running
> out of time at the moment.
>
> No problem, customers never read documentations. [image: :smirk:]
>
> But I don't know what to do.
>
> Did you translate it "manually"? [image: :flushed:]
>
> It's really simple:
>
>    - add french to "obpm.pro" ("TRANSLATIONS += lng/obpm_de.ts
>    lng/obpm_fr.ts")
>    - update translations ("lupdate -no-obsolete obpm.pro") -> copy your
>    already existing translated file to "lng/obpm_fr.ts" before or you get a
>    new empty file!
>    - translate all new/updated strings ("linguist lng/obpm_fr.ts")
>    - click on "File -> Release" to create the tranlation file
>    "obpm_fr.qm" and run obpm to see if all is fine
>
> The "lupdate" (command line tool) and "linguist" (gui) are components of
> Qt <https://www.qt.io/download-open-source/>.
>
> Your current file is broken ("+" signs at line 1280/1281) and the strings
> "LazyT" should be replaced by "patlachance" (or whatever should be shown in
> about dialog) and "English" should be "Français".
>
> I can fix this for you, checkin to github and close this request or would
> you like to try the above yourself?
>
> Greetings,
> Thomas
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/LazyT/obpm/pull/6#issuecomment-217095359>
>



-- 
Patrice LACHANCE

Social networks:
    Viadeo:    http://www.viadeo.com/profile/00226pj42r07h9f3
    LinkedIn:  http://www.linkedin.com/in/plachance

**Pull request merged**
